### ISSUE TITLE
[Questions] how to enable playback speed controls on video overlay? 

### ISSUE THREAD

**Issue by vikas1255** [arichorn/YouTubeRebornPlus#59]
### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Is there an existing issue/question for this?

- [X] I have searched the existing issues

### Do you think this is a bug?

❌ No, I don't think this is a bug. I will explain below

### My question

May be I am missing something here as playback speed control on video overlay is  a sought after feature. How to make it work?

**Comment by vikas1255** [comment]
I tried that. I think that this option is not related to overlay. It increased the no. of speed control option inside the menu though. 
![IMG_1519](https://github.com/arichorn/YouTubeRebornPlus/assets/83866361/5631cec9-dde7-445d-ae06-bc33a22e2e8c)

![IMG_1520](https://github.com/arichorn/YouTubeRebornPlus/assets/83866361/daac6dff-a618-4c9e-b3cd-e5217129daa0)

**Comment by vikas1255** [comment]
Thanks but iPad layout option also is not able to show the playback speed control as an overlay. It changed the layout though. 

![IMG_1522](https://github.com/arichorn/YouTubeRebornPlus/assets/83866361/93b3d0cc-8de5-4750-b937-929362dc5f0f)
![IMG_1521](https://github.com/arichorn/YouTubeRebornPlus/assets/83866361/a0e649d5-c83f-4d4e-a0aa-68dbc4377924)

**Comment by rakleed** [comment]
@vikas1255 @arichorn when choosing v18.18.2 and below, YTSpeed ​​starts working again.

**Comment by rakleed** [comment]
@vikas1255 @arichorn when choosing `v18.18.2` and below, YTSpeed ​​starts working again.

@arichorn is there any way to make YTSpeed ​​compatible with the latest YouTube versions?

**Comment by vikas1255** [comment]
Thanks a lot.
